spring:
  datasource:
    url: jdbc:mysql://localhost:3303/library_db
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: db/changelog/changelog.xml
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 16MB
      max-request-size: 32MB
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth:true
          starttls.enable
server:
  port: 8090